//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanEntity
    {
        public string Loan_Account_ID { get; set; }
        public string Customer_ID { get; set; }
        public float Loan_Amount { get; set; }
        public System.DateTime LStart_Date { get; set; }
        public int Tenure { get; set; }
        public float Loan_ROI { get; set; }
        public float EMI { get; set; }
        public float Outstanding { get; set; }
    
        public virtual AccountsEntity AccountsEntity { get; set; }
        public virtual CustomerEntity CustomerEntity { get; set; }
    }
}
