//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsEntity
    {
        public string Account_ID { get; set; }
        public string Customer_ID { get; set; }
        public float Balance { get; set; }
    
        public virtual AccountsEntity AccountsEntity { get; set; }
        public virtual CustomerEntity CustomerEntity { get; set; }
    }
}
